name: Generate 3D Contributions
on:
  schedule:
    - cron: '0 17 * * *'  # 00:00 WIB daily
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@0.9.1
        with:
          username: HaikalFaruq
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit & push
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore: update 3D contribution graphs"
            git push
          fi
