name: WakaTime Readme

on:
  schedule:
    - cron: "0 0 * * *"   # jalan tiap hari jam 00:00 UTC
  workflow_dispatch:       # bisa dijalankan manual

jobs:
  update-readme:
    name: Update WakaTime Stats
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
